package io.petermueller.petrinetz.util;

public enum Event {
	FILESYSTEM_NEW_FILE_OPENED,
	FILESYSTEM_INVALID_FILE,
	PETRINET_TRANSITION_FIRED,
	PETRINET_USER_SELECTED_A_PLACE,
	PETRINET_MARKING_RESET,
	PETRINET_MARKING_EDITED,
	PETRINET_NEW_NET_LOADED,
	RGRAPH_NEW_NODE_ADDED,
	RGRAPH_RESET,
	RGRAPH_SET_TO_MARKING,
	RGRAPH_NEW_GRAPH_LOADED;
}
